name: check_in

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    name: do_checkin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: run
        run: python3 cqupt_checkin.py ${{secrets.USERNAME}} ${{secrets.PASSWORD}} ${{secrets.LONGITUDE}} ${{secrets.LATITUDE}} ${{secrets.ADDRESS}} 
